version: '3.0'

services:
    mysql:
      image: mysql:5.7
      container_name: xg_mysql
      restart: always
      environment:
          MYSQL_DATABASE: 'db'
          MYSQL_USER: 'admin'
          MYSQL_PASSWORD: 'Bada123'
          MYSQL_DATABASE: 'xg'
          MYSQL_ROOT_PASSWORD: 'Badanamu123456'
      volumes:
        - ./mysql/db:/var/lib/mysql
        - ./mysql/conf:/etc/mysql/conf.d
        - ./mysql/log:/var/log/mysql
        - ./mysql/init:/docker-entrypoint-initdb.d/
    redis:
      image: redis:latest
      container_name: xg_redis
      restart: always
      volumes:
        - ./redis/data:/data
        - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
        - ./redis/log:/logs
    nginx:
      restart: always
      image: nginx
      container_name: xg_nginx
      ports:
        - 80:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
        - ./nginx/conf.d:/etc/nginx/conf.d 
        - ./nginx/log:/var/log/nginx
        - ./nginx/www:/usr/share/nginx/wwwroot
    golang:
      image: golang:latest
      container_name: xg_golang
      restart: always
      environment:
        xg_db_conn: 'root:Badanamu123456@tcp(mysql:3306)/xg?parseTime=true&charset=utf8mb4'
        xg_redis_conn: 'redis:6379'
        xg_log_path: '/var/log'
        xg_upload_path: '/go/uploads'
      ports:
        - 8088:8088
      volumes:
        - ./golang/bin:/go/bin 
        - ./golang/uploads:/go/uploads 
        - ./golang/log:/var/log
      depends_on:
        - mysql
        - redis
      command: 
        - /go/bin/xg